CREATE TABLE user (
	id_user INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	email  VARCHAR(255),
    role VARCHAR(12) NOT NULL,
    picture VARCHAR(255),
    password VARCHAR(255) NOT NULL,
	CONSTRAINT UC_user UNIQUE (email)
);
